version: '2'
services:
  daemon:
    hostname: daemon
    build: daemon
    ports:
      - "2022:2022"
    tty: true
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:s1.node.occultus.network"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/srv/daemon/config/"
      - "/home/daemon-data:/home/daemon-data/"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"

networks:
  default:
    external:
      name: proxy
