version: '2'
services:
  daemon:
    hostname: daemon
    build: daemon
    ports:
      - "2022:2022"
      - "8080:8080"
    tty: true
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/:/srv/daemon/config/"
      - "./server-data/:/srv/daemon-data/"
